- name: Copy Root CA Cert
  ansible.builtin.copy:
    content: "{{ rootca_cert }}"
    dest: /etc/elasticsearch/certs/cacert.pem
    owner: elasticsearch
    group: elasticsearch
  become: true

- name: Copy Server private key
  ansible.builtin.copy:
    content: "{{ server_private_key }}"
    dest: /etc/elasticsearch/certs/server.key
    owner: elasticsearch
    group: elasticsearch
    mode: '0400'
  become: true

- name: Copy Server certificate
  ansible.builtin.copy:
    content: "{{ server_cert }}"
    dest: /etc/elasticsearch/certs/server.cer
    owner: elasticsearch
    group: elasticsearch
  become: true

- name: Copy Root CA to certificate store
  ansible.builtin.copy:
    src: "/etc/elasticsearch/certs/cacert.pem"
    dest: /etc/pki/ca-trust/source/anchors/cacert.pem
    remote_src: true
    mode: 0644
  become: true

- name: Update CA Trust
  ansible.builtin.command: update-ca-trust
  register: update_ca_trust
  changed_when: update_ca_trust.rc == 0
  become: true