---
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
secrets_endpoint: "{{ 'https://secretsmanager-fips.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', endpoint=ssm_endpoint) }}"
prisma_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/prisma_secrets_path', endpoint=ssm_endpoint) }}"

ssm_parameter_store_key_id: "{{ lookup('amazon.aws.aws_ssm', '/production/ssm_parameter_store_key_id', endpoint=ssm_endpoint) }}"

# Install DSM
prisma_license: "{{ lookup('amazon.aws.aws_ssm', prisma_secrets_path + 'prisma_license', endpoint=ssm_endpoint) }}"
admin_password: "{{ lookup('amazon.aws.aws_ssm', prisma_secrets_path + 'admin_password', endpoint=ssm_endpoint) }}"
