---
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
secrets_endpoint: "{{ 'https://secretsmanager-fips.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', endpoint=ssm_endpoint) }}"
dsm_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/trenddsm_secrets_path', endpoint=ssm_endpoint) }}"

ssm_parameter_store_key_id: "{{ lookup('amazon.aws.aws_ssm', '/production/ssm_parameter_store_key_id', endpoint=ssm_endpoint) }}"

# Install DSM
dsm_license: "{{ lookup('amazon.aws.aws_ssm', dsm_secrets_path + 'dsm_license', endpoint=ssm_endpoint, on_missing='skip') }}"
dsm_admin_password: "{{ lookup('amazon.aws.aws_ssm', dsm_secrets_path + 'masteradmin', endpoint=ssm_endpoint) }}"
db_endpoint: "{{ lookup('amazon.aws.aws_ssm', dsm_secrets_path + 'db_endpoint', endpoint=ssm_endpoint) }}"
db_password: "{{ lookup('amazon.aws.aws_ssm', dsm_secrets_path + 'db_password', endpoint=ssm_endpoint) }}"

# Setup DSM
alb_hostname: "{{ lookup('amazon.aws.aws_ssm', dsm_secrets_path + 'alb_hostname', endpoint=ssm_endpoint) }}"

dsm_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'dsm_cert', endpoint=ssm_endpoint) }}"
dsm_cert_key: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'dsm_cert_key', endpoint=ssm_endpoint) }}"
rootca_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'root_ca_pub.pem', endpoint=ssm_endpoint) }}"

# LDAP
svc_trenddsm_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_trenddsm', endpoint=ssm_endpoint, on_missing='skip') }}"
dom_disname: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'dom_disname', endpoint=ssm_endpoint, on_missing='skip') }}"

# Logging
deployed_siem: "{{ lookup('amazon.aws.aws_ssm', '/production/siem', endpoint=ssm_endpoint, on_missing='skip') }}"
configure_log_ingest: "{{ lookup('amazon.aws.aws_ssm', dsm_secrets_path + 'configure_log_ingest', endpoint=ssm_endpoint) }}"
