- name: Stop Jira
  ansible.builtin.service:
    name: jira.service
    state: stopped
    enabled: true
  become: true

- name: Set sharedhome permissions
  ansible.builtin.file:
    path: /sharedhome
    owner: jira
    group: jira
    state: directory
    mode: "0755"
  become: true

- name: Copy Directories
  ansible.builtin.copy:
    src: "/var/atlassian/application-data/jira/{{ item }}"
    dest: "/sharedhome"
    remote_src: true
    owner: jira
    group: jira
    mode: preserve
  become: true
  loop:
    - data
    - plugins
    - logos
    - import
    - export
    - caches
    - keys

- name: Create backup folder
  ansible.builtin.file:
    path: /sharedhome/backup
    owner: jira
    group: jira
    state: directory
    mode: "0755"
  become: true

- name: Copy cluster.properties from template
  ansible.builtin.template:
    src: cluster.properties.j2
    dest: /var/atlassian/application-data/jira/cluster.properties
    mode: "0664"
    owner: jira
    group: jira
    force: true
  become: true

- name: Start Jira
  ansible.builtin.service:
    name: jira.service
    state: started
  become: true
  notify: Pause # Adding pause as it takes a minute or two before Jira fully loads

# Flush handlers to delete tempfiles and start pause now
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Slurp dbconfig.xml
  ansible.builtin.slurp:
    src: /var/atlassian/application-data/jira/dbconfig.xml
  register: slurp_dbconfig_backup
  become: true

- name: Copy dbconfig.xml
  ansible.builtin.copy:
    content: "{{ slurp_dbconfig_backup['content'] | b64decode }}"
    dest: /sharedhome/backup/dbconfig.xml
    owner: jira
    group: jira
    mode: preserve
  become: true
