- name: rhel update ca trust
  ansible.builtin.command: update-ca-trust
  register: update_ca_trust
  changed_when: update_ca_trust.rc == 0
  become: true

- name: ubuntu update ca trust
  ansible.builtin.command: update-ca-certificates
  register: update_ca_trust_ansible
  changed_when: update_ca_trust_ansible.rc == 0
  become: true

- name: restart xrdp
  ansible.builtin.service:
    name: xrdp
    state: restarted
    enabled: true
  become: true
