- name: Set Download URL based on OS version
  ansible.builtin.set_fact:
    download_url: "{{ manager_url }}software/agent/{{ platform_version }}{{ major_version }}/x86_64/{{ package }}"

- name: Download Trend Agent installer
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "/tmp/{{ package }}"
    force: true
    mode: "0755"
    validate_certs: false
  register: download_trend_agent
  delay: 60
  retries: 2
  until: download_trend_agent is not failed # Noticed intermittent download failures, adding retry as workaround

# - name: RHEL - Check Signature
#  ansible.builtin.command:
#    cmd: "rpm --checksig /tmp/{{ package }}"
#  when: ansible_facts['os_family'] == 'RedHat'

# - name: Ubuntu - Check Signature
#  ansible.builtin.command:
#    cmd: "dpkg-sig --verify /tmp/{{ package }}"
#  when: ansible_facts['distribution'] == 'Ubuntu'

- name: RHEL - Install Trend agent
  ansible.builtin.yum:
    name: "/tmp/{{ package }}"
    disable_gpg_check: true
    validate_certs: false # dsm uses self-signed certs
    state: present
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Ubuntu - Install Trend agent
  ansible.builtin.apt:
    deb: "/tmp/{{ package }}"
    state: present
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Configure FIPS
  ansible.builtin.copy:
    content: FIPSMode=1
    dest: /etc/ds_agent.conf
    force: true
    mode: "0644"
  become: true

# Comment out DS Agent cert, not working
# - name: Copy DS Agent Public certificate
#  ansible.builtin.copy:
#    content: "{{ rootca_cert }}"
#    dest: /var/opt/ds_agent/dsa_core/ds_agent_dsm_public_ca.crt
#    force: true
#  become: true

- name: Activate Trend Agent
  ansible.builtin.command:
    cmd: "{{ item }}"
  become: true
  loop:
    - /opt/ds_agent/dsa_control -r
    - "/opt/ds_agent/dsa_control -a {{ activation_url }} policy:'{{ policy_name }}'"
  when: not is_packer # Skip agent activation for a Packer build, activate instead in User Data to avoid duplication
  register: activate_trend_agent
  changed_when: activate_trend_agent.rc == 0

- name: Debug activate_trend_agent
  ansible.builtin.debug:
    var: activate_trend_agent
