### Domain Controller Policy ###
- name: Find Authlite DC GPO
  ansible.builtin.find:
    paths: "{{ role_path }}/files/authlite/DC"
    recurse: false
    file_type: directory
  register: authlite_dc_gpo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Copy Authlite DC GPO
  ansible.windows.win_copy:
    src: "{{ authlite_dc_gpo.files[0].path }}"
    dest: "{{ app_dir }}GPOs"
    recurse: true
    force: true

- name: Find Authlite DC bkupinfo.xml
  ansible.builtin.find:
    paths: "{{ role_path }}/files/authlite/DC"
    patterns: "bkupInfo.xml"
    recurse: true
  register: authlite_dc_gpo_bkupinfo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Read Authlite DC GPO XML
  community.general.xml:
    path: "{{ authlite_dc_gpo_bkupinfo.files[0].path }}"
    content: text
    xpath: "{{ item }}"
    namespaces:
      x: "http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  register: authlite_dc_xml
  delegate_to: localhost
  loop:
    - /x:BackupInst/x:GPOGuid
    - /x:BackupInst/x:GPODomain
    - /x:BackupInst/x:GPODomainGuid
    - /x:BackupInst/x:GPODomainController
    - /x:BackupInst/x:BackupTime
    - /x:BackupInst/x:ID
    - /x:BackupInst/x:Comment
    - /x:BackupInst/x:GPODisplayName

### Computer Policy ###
- name: Find Authlite Computer GPO
  ansible.builtin.find:
    paths: "{{ role_path }}/files/authlite/Computer"
    recurse: false
    file_type: directory
  register: authlite_computer_gpo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Copy Authlite Computer GPO
  ansible.windows.win_copy:
    src: "{{ authlite_computer_gpo.files[0].path }}"
    dest: "{{ app_dir }}GPOs"
    recurse: true
    force: true

- name: Find Authlite Computer bkupinfo.xml
  ansible.builtin.find:
    paths: "{{ role_path }}/files/authlite/Computer"
    patterns: "bkupInfo.xml"
    recurse: true
  register: authlite_computer_gpo_bkupinfo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Read Authlite Computer GPO XML
  community.general.xml:
    path: "{{ authlite_computer_gpo_bkupinfo.files[0].path }}"
    content: text
    xpath: "{{ item }}"
    namespaces:
      x: "http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  register: authlite_computer_xml
  delegate_to: localhost
  loop:
    - /x:BackupInst/x:GPOGuid
    - /x:BackupInst/x:GPODomain
    - /x:BackupInst/x:GPODomainGuid
    - /x:BackupInst/x:GPODomainController
    - /x:BackupInst/x:BackupTime
    - /x:BackupInst/x:ID
    - /x:BackupInst/x:Comment
    - /x:BackupInst/x:GPODisplayName
