- name: Read Base GPO XML
  community.general.xml:
    path: "{{ item.files[0].path }}"
    content: text
    xpath: "{{ bkupinfo_item }}"
    namespaces:
      x: "http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  register: base_xml
  delegate_to: localhost
  loop: "{{ bkupinfo_xpaths }}"
  loop_control:
    loop_var: bkupinfo_item

- name: Create base_gpo_xml_loop_item
  ansible.builtin.set_fact:
    base_gpo_xml_loop_item:
      - GPOGuid: "{{ base_xml.results[0].matches[0].values() | first }}"
        GPODomain: "{{ base_xml.results[1].matches[0].values() | first }}"
        GPODomainGuid: "{{ base_xml.results[2].matches[0].values() | first }}"
        GPODomainController: "{{ base_xml.results[3].matches[0].values() | first }}"
        BackupTime: "{{ base_xml.results[4].matches[0].values() | first }}"
        ID: "{{ base_xml.results[5].matches[0].values() | first }}"
        Comment: "{{ base_xml.results[6].matches[0].values() | first }}"
        GPODisplayName: "{{ base_xml.results[7].matches[0].values() | first }}"

- name: Append Base XML list
  ansible.builtin.set_fact:
    base_gpo_xml_list: "{{ base_gpo_xml_list + base_gpo_xml_loop_item }}"
