---
- name: Load AWS vars
  ansible.builtin.include_vars: aws.yml
  when: ansible_system_vendor == 'Amazon EC2'
  tags:
    - always

- name: NGEN powershell assembly, improves startup time of powershell by 10x
  ansible.windows.win_powershell:
    script: |
      $old_path = $env:path
      try {
        $env:path = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
        [AppDomain]::CurrentDomain.GetAssemblies() | % {
          if (! $_.location) {continue}
          $Name = Split-Path $_.location -leaf
          if ($Name.startswith("Microsoft.PowerShell.")) {
            Write-Progress -Activity "Native Image Installation" -Status "$name"
            ngen.exe install $_.location | % {"`t$_"}
          }
        }
      } finally {
        $env:path = $old_path
      }
    error_action: stop
  register: ps_ngen
  tags:
    - initial

- name: Install AD
  ansible.builtin.include_tasks: install_ad.yml
  tags:
    - initial

- name: Config AD
  ansible.builtin.include_tasks: config_ad.yml
  tags:
    - initial

- name: Create AWS AD Backup Scheduled task
  ansible.builtin.include_tasks: aws_ad_backup.yml
  when: ansible_system_vendor == 'Amazon EC2'
  tags:
    - initial

- name: Create Organizational Units
  ansible.builtin.include_tasks: organizational_units.yml
  tags:
    - initial

- name: Create Default Groups and Users
  ansible.builtin.include_tasks: default_groups_and_users.yml
  tags:
    - initial

- name: Set GPOs
  ansible.builtin.include_tasks: gpos.yml
  tags:
    - gpo

- name: Install Authlite
  ansible.builtin.include_tasks: install_authlite.yml
  when: install_authlite | bool
  tags:
    - gpo

- name: Run AWS Workspaces tasks
  ansible.builtin.include_tasks: workspaces.yml
  when: ansible_system_vendor == 'Amazon EC2'
  tags:
    - workspaces
