### Domain Controller Policy ###
- name: Find AWS STIG DC GPO
  ansible.builtin.find:
    paths: "{{ role_path }}/files/aws/STIG/GPOs/DC"
    recurse: false
    file_type: directory
  register: dc_gpo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Copy DC GPO
  ansible.windows.win_copy:
    src: "{{ dc_gpo.files[0].path }}"
    dest: "{{ app_dir }}GPOs"
    recurse: true
    force: true

- name: Find AWS STIG DC bkupinfo.xml
  ansible.builtin.find:
    paths: "{{ role_path }}/files/aws/STIG/GPOs/DC"
    patterns: "bkupInfo.xml"
    recurse: true
  register: dc_gpo_bkupinfo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Read STIG DC GPO XML
  community.general.xml:
    path: "{{ dc_gpo_bkupinfo.files[0].path }}"
    content: text
    xpath: "{{ item }}"
    namespaces:
      x: "http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  register: dc_xml
  delegate_to: localhost
  loop:
    - /x:BackupInst/x:GPOGuid
    - /x:BackupInst/x:GPODomain
    - /x:BackupInst/x:GPODomainGuid
    - /x:BackupInst/x:GPODomainController
    - /x:BackupInst/x:BackupTime
    - /x:BackupInst/x:ID
    - /x:BackupInst/x:Comment
    - /x:BackupInst/x:GPODisplayName

### Server Policy ###
- name: Find AWS STIG Server GPO
  ansible.builtin.find:
    paths: "{{ role_path }}/files/aws/STIG/GPOs/Server"
    recurse: false
    file_type: directory
  register: server_gpo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Copy Server GPO
  ansible.windows.win_copy:
    src: "{{ server_gpo.files[0].path }}"
    dest: "{{ app_dir }}GPOs"
    recurse: true
    force: true

- name: Find AWS STIG Server bkupinfo.xml
  ansible.builtin.find:
    paths: "{{ role_path }}/files/aws/STIG/GPOs/Server"
    patterns: "bkupInfo.xml"
    recurse: true
  register: server_gpo_bkupinfo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Read STIG Server GPO XML
  community.general.xml:
    path: "{{ server_gpo_bkupinfo.files[0].path }}"
    content: text
    xpath: "{{ item }}"
    namespaces:
      x: "http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  register: server_xml
  delegate_to: localhost
  loop:
    - /x:BackupInst/x:GPOGuid
    - /x:BackupInst/x:GPODomain
    - /x:BackupInst/x:GPODomainGuid
    - /x:BackupInst/x:GPODomainController
    - /x:BackupInst/x:BackupTime
    - /x:BackupInst/x:ID
    - /x:BackupInst/x:Comment
    - /x:BackupInst/x:GPODisplayName

### User Policy ###
- name: Find AWS STIG User GPO
  ansible.builtin.find:
    paths: "{{ role_path }}/files/aws/STIG/GPOs/User"
    recurse: false
    file_type: directory
  register: user_gpo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Copy User GPO
  ansible.windows.win_copy:
    src: "{{ user_gpo.files[0].path }}"
    dest: "{{ app_dir }}GPOs"
    recurse: true
    force: true

- name: Find AWS STIG User bkupinfo.xml
  ansible.builtin.find:
    paths: "{{ role_path }}/files/aws/STIG/GPOs/User"
    patterns: "bkupInfo.xml"
    recurse: true
  register: user_gpo_bkupinfo
  delegate_to: localhost
  when:
    - ansible_system_vendor == 'Amazon EC2'

- name: Read STIG User GPO XML
  community.general.xml:
    path: "{{ user_gpo_bkupinfo.files[0].path }}"
    content: text
    xpath: "{{ item }}"
    namespaces:
      x: "http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  register: user_xml
  delegate_to: localhost
  loop:
    - /x:BackupInst/x:GPOGuid
    - /x:BackupInst/x:GPODomain
    - /x:BackupInst/x:GPODomainGuid
    - /x:BackupInst/x:GPODomainController
    - /x:BackupInst/x:BackupTime
    - /x:BackupInst/x:ID
    - /x:BackupInst/x:Comment
    - /x:BackupInst/x:GPODisplayName

### Link GPOs ###
- name: Create a file from a Jinja2 template
  ansible.windows.win_template:
    src: stig/manifest.xml.j2
    dest: "{{ app_dir }}GPOs\\manifest.xml"

- name: Import GPOs
  ansible.windows.win_powershell:
    script: |
      Import-Module -Name GroupPolicy

      #Assign GPOs
      $Manifest = "{{ gpo_path }}manifest.xml"
      [xml]$ManifestData = Get-Content $Manifest
      foreach ($GPO in $ManifestData.Backups.BackupInst) {
        Import-GPO -BackupId $GPO.ID."#cdata-section" -TargetName $GPO.GPODisplayName."#cdata-section" -MigrationTable `
        "{{ gpo_path }}gpo-migtable.migtable" -CreateIfNeeded `
        -Path {{ gpo_path }} -Verbose
      }
    error_action: stop
  register: import_gpos
  changed_when: import_gpos.verbose | select("match", ".*Import the GPO backup.*")

# Note: Link order for each matching target is extremely important.  Must go from lowest to highest or command will error.
- name: Link GPOs
  ansible.windows.win_powershell:
    script: "{{ lookup('ansible.builtin.template', 'stig/gplink.ps1.j2') }}"
    error_action: stop
  register: link_gpos
  changed_when: link_gpos.verbose | select("match", ".*Create a link from.*")
