---
# Common
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', endpoint=ssm_endpoint) }}"
tower_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/tower_secrets_path', endpoint=ssm_endpoint) }}"

install_s3_bucket: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'install_s3_bucket', endpoint=ssm_endpoint) }}"
dom_disname: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'dom_disname', endpoint=ssm_endpoint) }}"
alb_hostname: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'alb_hostname', endpoint=ssm_endpoint) }}"

# Create API Token
tower_password: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'admin', endpoint=ssm_endpoint) }}"

# Organization
tower_org_name: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'tower_org_name', endpoint=ssm_endpoint) }}"

# Inventory
prod_account_role_arn: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'prod_account_role_arn', endpoint=ssm_endpoint) }}"
staging_account_role_arn: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'staging_account_role_arn', endpoint=ssm_endpoint) }}"

# Project
code_commit_url: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'code_commit_url', endpoint=ssm_endpoint) }}"

# SQS Cleanup
ec2_term_queue_name: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'ec2_term_queue_name', endpoint=ssm_endpoint) }}"

# LDAP
svc_ansibletwr_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansibletwr', endpoint=ssm_endpoint) }}"
svc_ansible_da_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible_da', endpoint=ssm_endpoint) }}"

# Credentials
svc_ansible_pass: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible', endpoint=ssm_endpoint) }}"

# Logging
deployed_siem: "{{ lookup('amazon.aws.aws_ssm', '/production/siem', endpoint=ssm_endpoint) }}"
splunk_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/splunk_secrets_path', endpoint=ssm_endpoint, on_missing='skip') }}"
user_password: "{{ lookup('amazon.aws.aws_ssm', splunk_secrets_path + 'user_password', endpoint=ssm_endpoint, on_missing='skip') }}"
configure_log_ingest: "{{ lookup('amazon.aws.aws_ssm', tower_secrets_path + 'configure_log_ingest', endpoint=ssm_endpoint) | bool }}"
