# https://www.elastic.co/guide/en/logstash/current/keystore.html
- name: Store keystore password env variable
  ansible.builtin.template:
    src: logstash.j2
    dest: /etc/sysconfig/logstash
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Ensure keystore file does not exist
  ansible.builtin.file:
    path: /etc/logstash/logstash.keystore
    state: absent
  become: true

- name: Create keystore file
  ansible.builtin.command:
    cmd: /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
  become: true
  register: create_keystore
  changed_when: create_keystore.stdout_lines | select("match", ".*Created Logstash keystore.*")
  environment:
    LOGSTASH_KEYSTORE_PASS: "{{ elastic_password }}"
  no_log: true
  
- name: Set elasticsearch password
  ansible.builtin.command:
    cmd: /usr/share/logstash/bin/logstash-keystore add ES_PWD --path.settings /etc/logstash --allow-root --stdin --force
    stdin: "{{ elastic_password }}"
  become: true
  register: set_elasticsearch_password
  changed_when: set_elasticsearch_password.stdout_lines | select("match", ".*Added 'es_pwd' to the Logstash keystore.*") 
  environment:
    LOGSTASH_KEYSTORE_PASS: "{{ elastic_password }}"
  no_log: true
