- name: Stop logstash
  ansible.builtin.service:
    name: logstash
    state: stopped
  become: true

- name: Copy Templates
  include_tasks: copy_templates.yml

- name: Configure Logstash keystore
  include_tasks: configure_keystore.yml

# This code attempts to set heap_size to half of total RAM
- name: Set heap_size
  ansible.builtin.set_fact:
    heap_size: "{{ (( ansible_memtotal_mb / 1024.0) | round(0, 'ceil') | int ) // 2 }}"
  tags:
    - molecule-notest

- name: Add 1 to heap_size if not even number
  ansible.builtin.set_fact:
    heap_size: "{{ heap_size | int + 1 }}"
  when: heap_size | int is not divisibleby 2
  tags:
    - molecule-notest

- name: Limit heap size to 8GB
  ansible.builtin.set_fact:
    heap_size: 8
  when: heap_size | int > 8
  tags:
    - molecule-notest

- name: Debug heap_size
  debug:
    var: heap_size
  tags:
    - molecule-notest

- name: Set JVM heap size
  ansible.builtin.lineinfile:
    path: /etc/logstash/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.heap_size_setting }}"
  become: true
  loop:
  - { regexp: '^-Xms1g', heap_size_setting: "-Xms{{ heap_size | default(1) }}g"}
  - { regexp: '^-Xmx1g', heap_size_setting: "-Xmx{{ heap_size | default(1) }}g"}

- name: Ensure correct permissions on /opt
  ansible.builtin.file:
    path: /opt
    owner: logstash
    group: logstash
    state: directory
    recurse: true
  become: true

- name: Restart logstash
  ansible.builtin.service:
    name: logstash
    state: restarted
    enabled: true
  become: true

- name: Pause 30 seconds
  ansible.builtin.pause:
    seconds: 30
