- name: Add Linux SSH Credential
  ansible.tower.tower_credential:
    name: Linux SSH
    description: Linux SSH Credential
    organization: "{{ tower_org_name }}"
    credential_type: Machine
    state: present
    inputs:
      become_method: sudo
      become_username: root
      become_password: "{{ svc_ansible_pass }}"
      username: "svc_ansible@{{ ansible_domain | upper }}"
      password: "{{ svc_ansible_pass }}"
    tower_host: "{{ tower_api_url }}"
    tower_oauthtoken: "{{ tower_token }}"

- name: Add Windows RM Credential
  ansible.tower.tower_credential:
    name: Windows WinRM
    description: Windows RM Credential
    organization: "{{ tower_org_name }}"
    credential_type: Machine
    state: present
    inputs:
      username: "svc_ansible@{{ ansible_domain | upper }}"
      password: "{{ svc_ansible_pass }}"
    tower_host: "{{ tower_api_url }}"
    tower_oauthtoken: "{{ tower_token }}"

- name: Add Ansible Galaxy
  ansible.tower.tower_credential:
    name: Ansible Galaxy
    description: Ansible Galaxy Credential
    organization: "{{ tower_org_name }}"
    credential_type: Ansible Galaxy/Automation Hub API Token
    state: present
    inputs:
      url: https://galaxy.ansible.com
    tower_host: "{{ tower_api_url }}"
    tower_oauthtoken: "{{ tower_token }}"

# Note: Avoiding circular dependency.  Credentials require an Organization, but galaxy credential cannot be specified if the credential doesn't exist.
# So I'm 1) creating an organization without Galaxy creds, 2) creating Credentials, 3) creating the org again with galaxy creds.
- name: Create tower organization with Galaxy creds
  ansible.tower.tower_organization:
    name: "{{ tower_org_name }}"
    description: "Production Organization"
    state: present
    tower_host: "{{ tower_api_url }}"
    tower_oauthtoken: "{{ tower_token }}"
    galaxy_credentials:
      - Ansible Galaxy
