- name: Copy Root CA file
  ansible.builtin.copy:
    content: "{{ rootca_cert }}"
    dest: /etc/pki/ca-trust/source/anchors/cacert.pem
    mode: '0644'
  become: true
  notify: Update CA Trust

- name: Copy Jira certificate
  ansible.builtin.copy:
    content: "{{ jira_cert }}"
    dest: /tmp/jira_cert.pem
    mode: '0644'
  become: true

- name: Copy Jira private key
  ansible.builtin.copy:
    content: "{{ jira_cert_key }}"
    dest: /tmp/jira_cert_key.pem
    mode: '0400'
  become: true
