---
- name: Load AWS vars
  ansible.builtin.include_vars: aws.yml
  when: ansible_system_vendor == 'Amazon EC2'

- name: Install Python Packages on Ansible host
  ansible.builtin.pip:
    name: python-gitlab
    state: present
    umask: "0022"
  become: true

- name: Get Initial Oauth token
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}oauth/token"
    method: POST
    body_format: form-urlencoded
    status_code: 200
    body:
      grant_type: password
      username: root
      password: "{{ initial_root_password }}"
  register: initial_oauth_token
  no_log: true

- name: Create Groups
  ansible.builtin.include_tasks: create_groups.yml

- name: Create Automation Admin User
  ansible.builtin.include_tasks: create_admin_user.yml

- name: Set Gitlab Application Settings
  ansible.builtin.include_tasks: set_application_settings.yml

- name: List projects
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}api/v4/projects"
    method: GET
    body_format: json
    status_code: 200
    headers:
      Authorization: "Bearer {{ initial_oauth_token.json.access_token }}"
  register: list_projects

- name: Import Projects from Github
  ansible.builtin.include_tasks: import_projects.yml
  loop: "{{ projects | dict2items }}"

- name: Revoke Initial Oauth token
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}oauth/revoke"
    method: POST
    body_format: form-urlencoded
    status_code: 200
    body:
      token: "{{ initial_oauth_token.json.access_token }}"
  register: revoke_oauth_token