- name: Post Setup Wait
  ansible.builtin.pause:
    minutes: 10

- name: rhel update ca trust
  ansible.builtin.command: update-ca-trust
  register: update_ca_trust
  changed_when: update_ca_trust.rc == 0
  become: true

- name: ubuntu update ca trust
  ansible.builtin.command: update-ca-certificates
  register: update_ca_trust
  changed_when: update_ca_trust.rc == 0
  become: true

- name: pause
  ansible.builtin.pause:
    minutes: 1
