---
# Common
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', endpoint=ssm_endpoint) }}"
gitlab_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/gitlab_secrets_path', endpoint=ssm_endpoint) }}"

db_password: "{{ lookup('amazon.aws.aws_ssm', gitlab_secrets_path + 'db_password', endpoint=ssm_endpoint) }}"
initial_root_password: "{{ lookup('amazon.aws.aws_ssm', gitlab_secrets_path + 'initial_root_password', endpoint=ssm_endpoint) }}"
db_endpoint: "{{ lookup('amazon.aws.aws_ssm', gitlab_secrets_path + 'db_endpoint', endpoint=ssm_endpoint) }}"
#alb_hostname: "{{ lookup('amazon.aws.aws_ssm', gitlab_secrets_path + 'alb_hostname', endpoint=ssm_endpoint) }}"

# LDAP
dom_disname: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'dom_disname', endpoint=ssm_endpoint) }}"
svc_ansible_da_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible_da', endpoint=ssm_endpoint) }}"
svc_gitlab_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_gitlab', endpoint=ssm_endpoint) }}"

# TLS
gitlab_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'gitlab_cert', endpoint=ssm_endpoint) }}"
gitlab_cert_key: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'gitlab_cert_key', endpoint=ssm_endpoint) }}"
rootca_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'root_ca_pub.pem', endpoint=ssm_endpoint) }}"

gitlab_db_rootcert: /etc/gitlab/ssl/rds-combined-bundle.pem

aws_s3_backup_bucket_name: "{{ lookup('amazon.aws.aws_ssm', gitlab_secrets_path + 'aws_s3_backup_bucket_name', endpoint=ssm_endpoint) }}"
s3_kms_key_arn: "{{ lookup('amazon.aws.aws_ssm', gitlab_secrets_path + 's3_kms_key_arn', endpoint=ssm_endpoint) }}"