- name: Create certs directory
  ansible.builtin.file:
    path: /etc/kibana/certs/
    state: directory
    owner: kibana
    group: kibana
    mode: "0755"
  become: true

- name: Copy kibana certificate
  ansible.builtin.copy:
    content: "{{ elastic_cert }}"
    dest: "/etc/kibana/certs/server.cer"
    owner: kibana
    group: kibana
    mode: "0644"
    force: true
  become: true

- name: Copy kibana private key
  ansible.builtin.copy:
    content: "{{ elastic_cert_key }}"
    dest: "/etc/kibana/certs/server.key"
    owner: kibana
    group: kibana
    mode: "0400"
    force: true
  become: true

- name: Copy Root CA file
  ansible.builtin.copy:
    content: "{{ rootca_cert }}"
    dest: "/etc/kibana/certs/cacert.pem"
    owner: kibana
    group: kibana
    mode: "0644"
    force: true
  become: true

- name: Copy Root CA file
  ansible.builtin.copy:
    content: "{{ rootca_cert }}"
    dest: "{{ root_ca_store }}"
    mode: "0644"
  become: true
  notify: "{{ update_ca_handler }}"
