---
- hosts: localhost
  connection: local
  vars:
    accounts:
      - name: mgmt
      - name: prod
        iam_role_arn: "{{ lookup('ansible.builtin.env', 'PROD_ACCOUNT_ROLE_ARN') }}"
      - name: stage
        iam_role_arn: "{{ lookup('ansible.builtin.env', 'STAGING_ACCOUNT_ROLE_ARN') }}"
  tasks:
    - name: Set is_gov
      ansible.builtin.set_fact:
        is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"

    - name: Template Initial Inventory Files
      ansible.builtin.template:
        src: /opt/ansible/templates/aws/init_aws_ec2.yml.j2
        dest: "/opt/ansible/inventory/aws/init/aws_ec2.yml"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0644"
      when: ansible_system_vendor == 'Amazon EC2'

    - name: Template Normal Inventory Files
      ansible.builtin.template:
        src: /opt/ansible/templates/aws/aws_ec2.yml.j2
        dest: "/opt/ansible/inventory/aws/run/{{ item.name }}_aws_ec2.yml"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0644"
      when: ansible_system_vendor == 'Amazon EC2'
      loop: "{{ accounts }}"
