- name: Set elasticsearch Password
  ansible.builtin.command:
    cmd: /usr/share/kibana/bin/kibana-keystore add elasticsearch.password --stdin --force
    stdin: "{{ elastic_password }}"
  become: true
  register: set_elasticsearch_pass
  changed_when: set_elasticsearch_pass.rc == 0
  no_log: true

- name: Set elasticsearch SSL passphrase
  ansible.builtin.command:
    cmd: /usr/share/kibana/bin/kibana-keystore add elasticsearch.ssl.keyPassphrase --stdin --force
    stdin: "{{ elastic_ssl_password }}"
  become: true
  register: set_elasticsearch_ssl_pass
  changed_when: set_elasticsearch_ssl_pass.rc == 0
  no_log: true

- name: Set server SSL passphrase
  ansible.builtin.command:
    cmd: /usr/share/kibana/bin/kibana-keystore add server.ssl.keyPassphrase --stdin --force
    stdin: "{{ elastic_ssl_password }}"
  become: true
  register: set_server_ssl_pass
  changed_when: set_server_ssl_pass.rc == 0
  no_log: true