- name: Configure DS URI in deploymentclient.conf
  community.general.ini_file:
    path: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    section: 'target-broker:deploymentServer'
    option: targetUri
    value: "{{ splunk_uri_ds }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_user }}"
    mode: "0644"
  become: true
  notify: restart splunk

- name: Configure client name in deploymentclient.conf
  community.general.ini_file:
    path: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    section: 'deployment-client'
    option: clientName
    value: "{{ inventory_hostname }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_user }}"
    mode: "0644"
  become: true
  notify: restart splunk

- name: Configure deployment server pass4SymmKey in server.conf
  community.general.ini_file:
    path: /opt/splunkforwarder/etc/system/local/server.conf
    section: deployment
    option: pass4SymmKey
    value: "{{ pass_4_symm_key }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_user }}"
    mode: "0644"
  become: true
  notify: restart splunk
