---
- name: Load AWS vars
  ansible.builtin.include_vars: aws.yml
  when: ansible_system_vendor == 'Amazon EC2'

- name: Set domain from Packer SSM
  ansible.builtin.set_fact:
    ansible_domain: "{{ lookup('amazon.aws.aws_ssm', '/production/packer/domain_name', endpoint=ssm_endpoint) }}"
  when:
    - ansible_system_vendor == 'Amazon EC2'
    - ansible_domain is not defined

- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ rolename_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: rolename_vars_file is file

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Install Splunk
  ansible.builtin.include_tasks: install_splunk.yml
  when: '"Splunkd.service" not in ansible_facts.services'

- name: Deploy Common Conf
  ansible.builtin.include_tasks: deploy_common_conf.yml
