---

gitlab_config_template: "gitlab.rb.j2"

# SSL Configuration.
gitlab_redirect_http_to_https: true
gitlab_ssl_certificate: "/etc/gitlab/ssl/server.crt" 
gitlab_ssl_certificate_key: "/etc/gitlab/ssl/server.key"

# LDAP Configuration.
gitlab_ldap_enabled: true
gitlab_ldap_port: "636"
gitlab_ldap_uid: "sAMAccountName"
gitlab_ldap_method: "simple_tls"
gitlab_ldap_bind_dn: "CN=svc_gitlab,OU=Service Accounts,OU=Management,OU=All Users,{{ dom_disname }}"
gitlab_ldap_bind_passwd: "{{ svc_gitlab_password }}"
gitlab_ldap_base: "OU=All Users,{{ dom_disname }}"
gitlab_ldap_group_base: "OU=Security Groups,OU=Management,OU=All Users,{{ dom_disname }}"
gitlab_ldap_admin_group: "GitlabAdmins"
gitlab_ldap_active_directory: true
gitlab_ldap_verify_certificates: true
gitlab_ldap_cert: "/etc/gitlab/ssl/cacert.pem"
gitlab_ldap_ssl_version: "TLSv1_2"  # "TLSv1_2"
gitlab_ldap_ciphers: "TLSv1.2+FIPS:kRSA+FIPS:!eNULL:!aNULL"  # "TLSv1.2+FIPS:kRSA+FIPS:!eNULL:!aNULL"

# PostgreSQL
gitlab_db_adapter: "postgresql"
gitlab_db_encoding: "unicode"
gitlab_db_username: "gitlab"

# 2-way SSL Client Authentication support.
gitlab_nginx_ssl_verify_client: ""
gitlab_nginx_ssl_client_certificate: ""

# Probably best to leave this as the default, unless doing testing.
gitlab_restart_handler_failed_when: 'gitlab_restart.rc != 0'

# Dependencies.
gitlab_dependencies:
  - openssh-server
  - postfix
  - curl
  - openssl
  - tzdata

# S3 setup for backups
aws_s3_region : "{{ aws_region }}"
aws_s3_bucket_name : "{{ resource_prefix }}-{{ aws_region }}-gitlab-backup"

