# Note: There is a warning that this feature will be disabled in a future release, however even when turned on through the UI
# this appears to be the only method of enabling Stack Monitoring through the API.  You should watch for a change with ELK 9.X
- name: Enable Monitoring
  ansible.builtin.uri:
    url: "{{ elastic_api_url }}/_cluster/settings"
    user: "elastic"
    url_password: "{{ elastic_password }}"
    method: PUT
    force_basic_auth: true
    status_code: 200, 409
    body_format: json
    body:
      persistent:
        xpack.monitoring.collection.enabled: true
  register: enable_monitoring

- name: Debug enable_monitoring
  ansible.builtin.debug:
    var: enable_monitoring
