windows_integration:
  policy_id: "{{ policy_id }}"
  package:
    name: windows
    version: "{{ package_version }}"
  name: windows-windows
  namespace: "{{ item.policy_namespace }}"
  inputs:
    windows-winlog:
      enabled: true
      streams:
        windows.forwarded:
          enabled: true
          vars:
            preserve_original_event: false
            ignore_older: 72h
            language: 0
            tags:
              - forwarded
        windows.powershell:
          enabled: true
          vars:
            preserve_original_event: false
            event_id: 400, 403, 600, 800
            ignore_older: 72h
            language: 0
            tags: []
        windows.powershell_operational:
          enabled: true
          vars:
            preserve_original_event: false
            event_id: 4103, 4104, 4105, 4106
            ignore_older: 72h
            language: 0
            tags: []
        windows.sysmon_operational:
          enabled: true
          vars:
            preserve_original_event: false
            ignore_older: 72h
            language: 0
            tags: []
    windows-windows/metrics:
      enabled: true
      streams:
        windows.perfmon:
          enabled: true
          vars:
            perfmon.group_measurements_by_instance: false
            perfmon.ignore_non_existent_counters: false
            perfmon.queries: |
              - object: 'Process'
                instance: ["*"]
                counters:
                - name: '% Processor Time'
                  field: cpu_perc
                  format: "float"
                - name: "Working Set"
            period: 10s
        windows.service:
          enabled: true
          vars:
            period: 60s
    windows-httpjson:
      enabled: false
      vars:
        url: https://server.example.com:8089
        ssl: |
          #certificate_authorities:
          #  - |
          #    -----BEGIN CERTIFICATE-----
          #    MIIDCjCCAfKgAwIBAgITJ706Mu2wJlKckpIvkWxEHvEyijANBgkqhkiG9w0BAQsF
          #    ADAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwIBcNMTkwNzIyMTkyOTA0WhgPMjExOTA2
          #    MjgxOTI5MDRaMBQxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEB
          #    BQADggEPADCCAQoCggEBANce58Y/JykI58iyOXpxGfw0/gMvF0hUQAcUrSMxEO6n
          #    fZRA49b4OV4SwWmA3395uL2eB2NB8y8qdQ9muXUdPBWE4l9rMZ6gmfu90N5B5uEl
          #    94NcfBfYOKi1fJQ9i7WKhTjlRkMCgBkWPkUokvBZFRt8RtF7zI77BSEorHGQCk9t
          #    /D7BS0GJyfVEhftbWcFEAG3VRcoMhF7kUzYwp+qESoriFRYLeDWv68ZOvG7eoWnP
          #    PsvZStEVEimjvK5NSESEQa9xWyJOmlOKXhkdymtcUd/nXnx6UTCFgnkgzSdTWV41
          #    CI6B6aJ9svCTI2QuoIq2HxX/ix7OvW1huVmcyHVxyUECAwEAAaNTMFEwHQYDVR0O
          #    BBYEFPwN1OceFGm9v6ux8G+DZ3TUDYxqMB8GA1UdIwQYMBaAFPwN1OceFGm9v6ux
          #    8G+DZ3TUDYxqMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAG5D
          #    874A4YI7YUwOVsVAdbWtgp1d0zKcPRR+r2OdSbTAV5/gcS3jgBJ3i1BN34JuDVFw
          #    3DeJSYT3nxy2Y56lLnxDeF8CUTUtVQx3CuGkRg1ouGAHpO/6OqOhwLLorEmxi7tA
          #    H2O8mtT0poX5AnOAhzVy7QW0D/k4WaoLyckM5hUa6RtvgvLxOwA0U+VGurCDoctu
          #    8F4QOgTAWyh8EZIwaKCliFRSynDpv3JTUwtfZkxo6K6nce1RhCWFAsMvDZL8Dgc0
          #    yvgJ38BRsFOtkRuAGSf6ZUwTO8JJRRIFnpUzXflAnGivK9M13D5GEQMmIl6U9Pvk
          #    sxSmbIUfc2SGJGCJD4I=
          #    -----END CERTIFICATE-----
      streams:
        windows.forwarded:
          enabled: false
          vars:
            interval: 10s
            search: search sourcetype="XmlWinEventLog:ForwardedEvents"
            tags:
              - forwarded
            preserve_original_event: false
        windows.powershell:
          enabled: false
          vars:
            interval: 10s
            search: search sourcetype="XmlWinEventLog:Windows PowerShell"
            tags:
              - forwarded
            preserve_original_event: false
        windows.powershell_operational:
          enabled: false
          vars:
            interval: 10s
            search: search sourcetype="XmlWinEventLog:Microsoft-Windows-Powershell/Operational"
            tags:
              - forwarded
            preserve_original_event: false
        windows.sysmon_operational:
          enabled: false
          vars:
            interval: 10s
            search: search sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational"
            tags:
              - forwarded
            preserve_original_event: false
