---
# Common
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"

application_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/' + app_name + '_secrets_path', endpoint=ssm_endpoint) }}"
application_db_host: "{{ lookup('amazon.aws.aws_ssm', application_secrets_path + 'db_endpoint', endpoint=ssm_endpoint) }}"
application_db_password: "{{ lookup('amazon.aws.aws_ssm', application_secrets_path + 'db_password', endpoint=ssm_endpoint) }}"
