# https://www.authlite.com/downloads/
# Note: Authlite does not provide a hash, it is simply calculated after download and only ensures that what you install in production
# is the same as what was installed in our sandbox.
win_authlite_download_url: https://s3.authlite.com/downloads/2.4/AuthLite_installer_x64.msi
win_authlite_installer_hash: 20fa5fc513df12d02be758b768835d5043ad5953b07b7b9f50e7ed62b28ff837
win_app_dir: "C:\\ProgramData\\Coalfire\\"
