- name: Load AWS vars
  ansible.builtin.include_vars: aws.yml
  when: ansible_system_vendor == 'Amazon EC2'

- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ rolename_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: rolename_vars_file is file

- name: Create Temp Files
  ansible.builtin.include_tasks: create_tempfiles.yml

- name: Revoke Old Certificates
  ansible.builtin.include_tasks: revoke_old_certs.yml

- name: Generate Certificates
  ansible.builtin.include_tasks: gen_certs.yml

- name: AWS Store Certs in SSM Parameter Store
  ansible.builtin.include_tasks: aws_store_certs_ssm.yml
  when: ansible_system_vendor == 'Amazon EC2'

- name: Remove Temp Files
  ansible.builtin.include_tasks: remove_tempfiles.yml
