---
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
secrets_endpoint: "{{ 'https://secretsmanager-fips.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', endpoint=ssm_endpoint) }}"
nessus_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/nessus_secrets_path', endpoint=ssm_endpoint) }}"

dom_disname: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'dom_disname', endpoint=ssm_endpoint) }}"
nessus_license: "{{ lookup('amazon.aws.aws_ssm', nessus_secrets_path + 'nessus_license', endpoint=ssm_endpoint) }}"
nessus_password: "{{ lookup('amazon.aws.aws_secret', nessus_secrets_path + 'nessus') }}"
rootca_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'root_ca_pub.pem', endpoint=ssm_endpoint) }}"
server_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'nessus_cert', endpoint=ssm_endpoint) }}"
server_cert_key: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'nessus_cert_key', endpoint=ssm_endpoint) }}"
svc_nessus_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_nessus', endpoint=ssm_endpoint) }}"
