name: "Packer Infrastructure Change Management Pipeline with GitHub Actions"

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  packer:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '#Build rhel-cis')
    name: "Packer Deployment"
    runs-on: [self-hosted, fastramp-3]
    container:
      image: ubuntu:23.04
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX_3_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX_3_AWS_SECRET_ACCESS_KEY }}
      volumes:
        - ${{ github.workspace }}:/packer
      options: --cpus 2

    steps:
      - name: Install Packages
        run: |
          apt update -y
          apt install -y git unzip

      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }} # or .head.ref for branch name
          path: fastramp-packer

      - name: Checkout the Ansible repository to the runner
        uses: actions/checkout@v3
        with: 
          repository: Coalfire-CF/fastramp-ansible
          path: fastramp-ansible
          ssh-key: ${{ secrets.FASTRAMP_ANSIBLE_REPO_DEPLOY_KEY }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.5" # or `latest`

      - name: Check dir
        id: ls
        run: ls -lah

      - name: packer init
        id: init
        run: packer init .
        working-directory: fastramp-packer/aws

      - name: packer validate
        id: validate
        run: packer validate -var-file=vars/variables.pkrvars.hcl .
        working-directory: fastramp-packer/aws

      - name: packer apply
        id: apply
        run: packer build -only="*rhel-cis*" -var-file=vars/variables.pkrvars.hcl .
        working-directory: fastramp-packer/aws