- name: Install OpenJDK
  ansible.builtin.package:
    name: "{{ openjdk_package_name }}"
    state: present
  become: true

- name: Find Java Home
  ansible.builtin.shell:
    cmd: java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | cut -f2 -d '='
  register: java_home_result
  changed_when: false

- name: Set ES_JAVA_HOME
  ansible.builtin.lineinfile:
    path: "{{ sysconfig_file }}"
    regexp: '^ES_JAVA_HOME='
    line: "ES_JAVA_HOME={{ java_home_result.stdout | trim }}/"
  become: true