---
# Common
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"

# Install/Configure AD
reverse_lookup_zone: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'reverse_lookup_zone', endpoint=ssm_endpoint) }}"
domain: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'domain', endpoint=ssm_endpoint) }}"
netbios: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'netbios', endpoint=ssm_endpoint) }}"
first_dc_ip: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'first_dc_ip', endpoint=ssm_endpoint) }}"
second_dc_ip: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'second_dc_ip', endpoint=ssm_endpoint) }}"
safe_mode_password: "{{ lookup('amazon.aws.aws_secret', ad_secrets_path + 'SafeMode') }}"

# Organizational Units
dom_disname: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'dom_disname', endpoint=ssm_endpoint) }}"

# Default Groups and Users
da_admin1_password: "{{ lookup('amazon.aws.aws_secret', ad_secrets_path + 'da_admin1') }}"
sa_admin1_password: "{{ lookup('amazon.aws.aws_secret', ad_secrets_path + 'sa_admin1') }}"
svc_ansible_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible', endpoint=ssm_endpoint) }}"
svc_ansible_da_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible_da', endpoint=ssm_endpoint) }}"
svc_dj_password: "{{ lookup('amazon.aws.aws_secret', ad_secrets_path + 'svc_dj') }}"

# Backup
ad_s3_backup_bucket: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'ad_s3_backup_bucket', endpoint=ssm_endpoint) }}"

# GPO
benchmark: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'benchmark', endpoint=ssm_endpoint) }}"
