---

# - name: "2.2.1 | PATCH | Ensure nis client is not installed"
#   package:
#       name: ypbind
#       state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
#   when:
#       - not amazon2cis_ypbind_required
#       - "'ypbind' in ansible_facts.packages"
#       - amazon2cis_rule_2_2_1
#   tags:
#       - level1
#       - automated
#       - patch
#       - rule_2.2.1
#       - nis

# - name: "2.2.2 | PATCH | Ensure rsh client is not installed"
#   package:
#       name: rsh
#       state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
#   when:
#       - not amazon2cis_rsh_required
#       - "'rsh' in ansible_facts.packages"
#       - amazon2cis_rule_2_2_2
#   tags:
#       - level1
#       - automated
#       - patch
#       - rule_2.2.2
#       - rsh

# - name: "2.2.3 | PATCH | Ensure talk client is not installed"
#   package:
#       name: talk
#       state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
#   when:
#       - not amazon2cis_talk_required
#       - "'talk' in ansible_facts.packages"
#       - amazon2cis_rule_2_2_3
#   tags:
#       - level1
#       - automated
#       - patch
#       - rule_2.2.3
#       - talk

# - name: "2.2.4 | PATCH | Ensure telnet client is not installed"
#   package:
#       name: telnet
#       state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
#   when:
#       - "'telnet' in ansible_facts.packages"
#       - not amazon2cis_telnet_required
#       - amazon2cis_rule_2_2_4
#   tags:
#       - level1
#       - automated
#       - patch
#       - rule_2.2.4
#       - telnet

# - name: "2.2.5 | PATCH | Ensure LDAP client is not installed"
#   package:
#       name: openldap-client
#       state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
#   when:
#       - not amazon2cis_openldap_clients_required
#       - "'openldap-client' in ansible_facts.packages"
#       - amazon2cis_rule_2_2_5
#   tags:
#       - level1
#       - automated
#       - patch
#       - rule_2.2.5
#       - ldap_client

---

- name: "2.2.1 | PATCH | Ensure nis client is not installed"
  shell: |
    if command -v dnf >/dev/null 2>&1; then
      dnf remove -y ypbind
    elif command -v yum >/dev/null 2>&1; then
      yum remove -y ypbind
    else
      echo "No supported package manager found"
      exit 1
    fi
  register: ypbind_remove
  failed_when: ypbind_remove.rc != 0 and "No match for argument" not in ypbind_remove.stderr and "No packages marked for removal" not in ypbind_remove.stdout
  changed_when: "'Nothing to do' not in ypbind_remove.stdout and 'No packages marked for removal' not in ypbind_remove.stdout"
  args:
    executable: /bin/bash
  when:
    - not amazon2cis_ypbind_required
    - amazon2cis_rule_2_2_1
  tags:
    - level1
    - automated
    - patch
    - rule_2.2.1
    - nis

- name: "2.2.2 | PATCH | Ensure rsh client is not installed"
  shell: |
    if command -v dnf >/dev/null 2>&1; then
      dnf remove -y rsh
    elif command -v yum >/dev/null 2>&1; then
      yum remove -y rsh
    else
      echo "No supported package manager found"
      exit 1
    fi
  register: rsh_remove
  failed_when: rsh_remove.rc != 0 and "No match for argument" not in rsh_remove.stderr and "No packages marked for removal" not in rsh_remove.stdout
  changed_when: "'Nothing to do' not in rsh_remove.stdout and 'No packages marked for removal' not in rsh_remove.stdout"
  args:
    executable: /bin/bash
  when:
    - not amazon2cis_rsh_required
    - amazon2cis_rule_2_2_2
  tags:
    - level1
    - automated
    - patch
    - rule_2.2.2
    - rsh

- name: "2.2.3 | PATCH | Ensure talk client is not installed"
  shell: |
    if command -v dnf >/dev/null 2>&1; then
      dnf remove -y talk
    elif command -v yum >/dev/null 2>&1; then
      yum remove -y talk
    else
      echo "No supported package manager found"
      exit 1
    fi
  register: talk_remove
  failed_when: talk_remove.rc != 0 and "No match for argument" not in talk_remove.stderr and "No packages marked for removal" not in talk_remove.stdout
  changed_when: "'Nothing to do' not in talk_remove.stdout and 'No packages marked for removal' not in talk_remove.stdout"
  args:
    executable: /bin/bash
  when:
    - not amazon2cis_talk_required
    - amazon2cis_rule_2_2_3
  tags:
    - level1
    - automated
    - patch
    - rule_2.2.3
    - talk

- name: "2.2.4 | PATCH | Ensure telnet client is not installed"
  shell: |
    if command -v dnf >/dev/null 2>&1; then
      dnf remove -y telnet
    elif command -v yum >/dev/null 2>&1; then
      yum remove -y telnet
    else
      echo "No supported package manager found"
      exit 1
    fi
  register: telnet_remove
  failed_when: telnet_remove.rc != 0 and "No match for argument" not in telnet_remove.stderr and "No packages marked for removal" not in telnet_remove.stdout
  changed_when: "'Nothing to do' not in telnet_remove.stdout and 'No packages marked for removal' not in telnet_remove.stdout"
  args:
    executable: /bin/bash
  when:
    - not amazon2cis_telnet_required
    - amazon2cis_rule_2_2_4
  tags:
    - level1
    - automated
    - patch
    - rule_2.2.4
    - telnet

- name: "2.2.5 | PATCH | Ensure LDAP client is not installed"
  shell: |
    if command -v dnf >/dev/null 2>&1; then
      dnf remove -y openldap-clients
    elif command -v yum >/dev/null 2>&1; then
      yum remove -y openldap-clients
    else
      echo "No supported package manager found"
      exit 1
    fi
  register: ldap_client_remove
  failed_when: ldap_client_remove.rc != 0 and "No match for argument" not in ldap_client_remove.stderr and "No packages marked for removal" not in ldap_client_remove.stdout
  changed_when: "'Nothing to do' not in ldap_client_remove.stdout and 'No packages marked for removal' not in ldap_client_remove.stdout"
  args:
    executable: /bin/bash
  when:
    - not amazon2cis_openldap_clients_required
    - amazon2cis_rule_2_2_5
  tags:
    - level1
    - automated
    - patch
    - rule_2.2.5
    - ldap_client
