---
# Common
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', region=aws_region, endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', region=aws_region, endpoint=ssm_endpoint) }}"
splunk_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/splunk_secrets_path', region=aws_region, endpoint=ssm_endpoint) }}"

pass_4_symm_key: "{{ lookup('amazon.aws.aws_ssm', splunk_secrets_path + 'pass_4_symm_key', region=aws_region, endpoint=ssm_endpoint) }}"
ssl_password: "{{ lookup('amazon.aws.aws_ssm', splunk_secrets_path + 'ssl_password', region=aws_region, endpoint=ssm_endpoint) }}"
user_password: "{{ lookup('amazon.aws.aws_ssm', splunk_secrets_path + 'user_password', region=aws_region, endpoint=ssm_endpoint) }}"

# TLS
cert_name: "{{ inventory_hostname | regex_replace('\\d$', '') }}"
splunkclient_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + cert_name + '_cert', region=aws_region, endpoint=ssm_endpoint) }}"
splunkclient_cert_key: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + cert_name + '_cert_key', region=aws_region, endpoint=ssm_endpoint) }}"
rootca_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'root_ca_pub.pem', region=aws_region, endpoint=ssm_endpoint) }}"
