splunk_file_name: "splunkforwarder-{{ splunk_package_version }}-{{ build_id }}.x86_64.rpm"
splunk_package_url: "https://download.splunk.com/products/universalforwarder/releases/{{ splunk_package_version }}/linux/{{ splunk_file_name }}"
splunk_installer_hash: b40b11ef5d4bf5fe78795ac89c57d30bb07b5c40d5404fc8a7b2cb6df20f49470b26127870b2b38dfd5a6850109c5d4e92ab1e2c0cd7a8f14c14351431c29ad9
# Append ".sha512" to the download URL to get the file hash
splunk_installer_name: splunk_uf.rpm
