---
# Common
aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
is_gov: "{{ lookup('ansible.builtin.env', 'IS_GOV') | bool }}"
ssm_fips_endpoint: "{% if is_gov %}ssm{% else %}ssm-fips{% endif %}"
ssm_endpoint: "{{ 'https://' + ssm_fips_endpoint + '.' + aws_region + '.amazonaws.com' }}"
ad_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ad_secrets_path', endpoint=ssm_endpoint) }}"
ca_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/ca_secrets_path', endpoint=ssm_endpoint) }}"
aap_secrets_path: "{{ lookup('amazon.aws.aws_ssm', '/production/aap_secrets_path', endpoint=ssm_endpoint) }}"

# aap
svc_ansible_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible', endpoint=ssm_endpoint) }}"
db_password: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'db_password', endpoint=ssm_endpoint) }}"
aap_admin: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'admin', endpoint=ssm_endpoint) }}"
install_s3_bucket: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'install_s3_bucket', endpoint=ssm_endpoint) }}"
install_s3_aap_file: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'install_s3_aap_file', endpoint=ssm_endpoint) }}"
db_endpoint: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'db_endpoint', endpoint=ssm_endpoint) }}"
aap_installer_hash: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'aap_installer_hash', endpoint=ssm_endpoint) }}"
rootca_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'root_ca_pub.pem', endpoint=ssm_endpoint) }}"
aapcontroller_cert: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'aapcontroller_cert', endpoint=ssm_endpoint) }}"
aapcontroller_cert_key: "{{ lookup('amazon.aws.aws_ssm', ca_secrets_path + 'aapcontroller_cert_key', endpoint=ssm_endpoint) }}"

# LDAP
dom_disname: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'dom_disname', endpoint=ssm_endpoint) }}"
svc_ansible_da_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_ansible_da', endpoint=ssm_endpoint) }}"
svc_aap_password: "{{ lookup('amazon.aws.aws_ssm', ad_secrets_path + 'svc_aap', endpoint=ssm_endpoint) }}"

alb_hostname: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'alb_hostname', endpoint=ssm_endpoint) }}"
ssh_user: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'ssh_user', endpoint=ssm_endpoint) }}"

ecr_repository_url: "{{ lookup('amazon.aws.aws_ssm', aap_secrets_path + 'ecr_repository_url', endpoint=ssm_endpoint) }}"