- name: Delegate to Ansible host
  delegate_to: localhost
  block:
    - name: Get Agent Policies
      ansible.builtin.uri:
        url: "{{ kibana_api_url }}/api/fleet/agent_policies"
        user: "elastic"
        url_password: "{{ elastic_password }}"
        method: GET
        force_basic_auth: true
        status_code: 200
      register: agent_policies
      changed_when: false

    - name: Set Fleet Server Policy ID
      ansible.builtin.set_fact:
        fleet_policy_id: "{{ agent_policies.json | community.general.json_query( field_query ) | first }}"
      vars:
        field_query: "items[?namespace=='fleet'].id"
