- name: RHEL tasks
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Import Elasticsearch GPG Key
      ansible.builtin.rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      become: true

    - name: Add repository
      ansible.builtin.yum_repository:
        name: elasticsearch
        description: Elasticsearch repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: true
        enabled: false
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      become: true

    - name: Install Elastic Agent
      ansible.builtin.yum:
        name: "elastic-agent-{{ elastic_version }}"
        enablerepo: elasticsearch
        state: present
      become: true
  # End RHEL tasks

- name: Ubuntu tasks
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    # Note: https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
    - name: Import Elasticsearch GPG Key
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /etc/apt/trusted.gpg.d/elastic.asc
        mode: "0644"
        force: true
      become: true

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
        state: present
      become: true

    - name: Install Elastic Agent
      ansible.builtin.apt:
        name: "elastic-agent={{ elastic_version }}"
        state: present
      become: true
  # End Ubuntu tasks
